# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Matematikk 1T
author: Kristoffer Stige
logo: logo.png

# Information about where the book exists on the web
description: >-
  Nettsider for Matematikk 1T

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: false


# HTML-specific settings
html:
  home_page_in_navbar         : false
  use_multitoc_numbering:   false

# Interact link settings
notebook_interface            : "notebook"

# Launch button settings

#binder:
#  binderhub_url               : "https://mybinder.org"
#  text                        : "Launch binder"

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: "xelatex"
  latex_documents:
    targetname: book.tex


# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib


# Information about where the book exists on the web
repository:
  url: https://kstige.github.io/Matematikk-1T  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

sphinx:
  recursive_update: true
  config:
    html_theme_options:
      repository_provider: github
    language: nb_NO

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
#html:
#  use_issues_button: true
#  use_repository_button: true


# GDPR
# sphinx:
#   config:
#     templates_path: ['_templates']

# html:
#   extra_navbar: |
#     <a href="#" id="open_preferences_center">Update cookies preferences</a>
